package:
  name: mirdeep2
  version: '2.0.0.8'

source:
  fn: mirdeep2_0_0_8.zip
  url: https://www.mdc-berlin.de/45995549/en/research/research_teams/systems_biology_of_gene_regulatory_elements/projects/miRDeep/mirdeep2_0_0_8.zip
  md5: a707f7d7ad4a2975fb8b2e78c5bcf483

build:
  number: 5

requirements:
  run:
    - perl-threaded
    - perl-pdf-api2
    - bowtie
    - viennarna
    - squid
    - randfold

about:
  home: https://www.mdc-berlin.de/8551903/en/
  license: academic
  summary: Discovering known and novel miRNAs from deep sequencing data
